---
- name: Setup user, install Docker, Java, and development tools
  hosts: all
  connection: ssh
  become: yes
  gather_facts: yes

  tasks:
    - name: Ensure group with GID 3300 exists
      group:
        name: distro
        gid: 3300
        state: present

    - name: Create user 'distro' with UID 1100 and GID 3300
      user:
        name: distro
        uid: 1100
        group: distro
        state: present
        shell: /bin/bash  # Specify shell if needed

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - unzip

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt package index after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Add user 'distro' to Docker group for Docker command permissions
      user:
        name: distro
        groups: docker
        append: yes

    - name: Restart Docker service to apply group permissions
      service:
        name: docker
        state: restarted

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Java 21
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Set Java 21 as the default version
      alternatives:
        name: java
        path: /usr/lib/jvm/java-21-openjdk-amd64/bin/java
        priority: 1100  # Higher priority makes Java 21 the default
        state: present

    - name: Set javac 21 as the default compiler version
      alternatives:
        name: javac
        path: /usr/lib/jvm/java-21-openjdk-amd64/bin/javac
        priority: 1100
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Download and install Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
        dest: /tmp/terraform.zip

    - name: Unzip Terraform
      unarchive:
        src: /tmp/terraform.zip
        dest: /tmp/
        remote_src: yes

    - name: Move Terraform binary to /usr/local/bin
      command: mv /tmp/terraform /usr/local/bin/

    - name: Clean up Terraform zip file
      file:
        path: /tmp/terraform.zip
        state: absent

    - name: Download and install Packer
      get_url:
        url: https://releases.hashicorp.com/packer/1.8.7/packer_1.8.7_linux_amd64.zip
        dest: /tmp/packer.zip

    - name: Unzip Packer
      unarchive:
        src: /tmp/packer.zip
        dest: /tmp/
        remote_src: yes

    - name: Move Packer binary to /usr/local/bin
      command: mv /tmp/packer /usr/local/bin/

    - name: Clean up Packer zip file
      file:
        path: /tmp/packer.zip
        state: absent


    - name: Install AWS CLI v2
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI v2
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes

    - name: Install AWS CLI v2
      command: ./aws/install
      args:
        chdir: /tmp/

    - name: Clean up AWS CLI installation files
      file:
        path: /tmp/awscliv2.zip
        state: absent

    - name: Remove AWS installation directory
      file:
        path: /tmp/aws
        state: absent
