name: Create AMI with Packer and Ansible

on:
  # push:
  #   branches: [master]
  workflow_dispatch:

jobs:
  build-ami:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          sudo apt-get update && sudo apt-get install -y packer

      # - name: Install Ansible
      #   run: |
      #     sudo apt update
      #     sudo apt install -y ansible

      - name: Set up AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "AWS credentials are set."

      - name: Initialize Packer
        run: |
          packer init ubuntu-ami.pkr.hcl

      - name: Build AMI with Packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRO_PUBLIC_KEY: ${{ secrets.DISTRO_PUBLIC_KEY }}
          DISTRO_SSH_PRIVATE_KEY: ${{ secrets.DISTRO_SSH_PRIVATE_KEY }}
        run: |
          COMMIT_ID=${GITHUB_SHA::8}
          packer build -var "public_key=\"${DISTRO_PUBLIC_KEY}\"" -var "private_key=\"${DISTRO_SSH_PRIVATE_KEY}\"" -var "commit_id=${COMMIT_ID}" ubuntu-ami.pkr.hcl

