name: Create AMI with Packer and Ansible

on:
  push:
    branches: [master]

jobs:
  build-ami:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Packer
        run: |
          # wget https://releases.hashicorp.com/packer/1.5.6/packer_1.5.6_linux_amd64.zip -O packer.zip
          # unzip packer.zip
          # sudo mv packer /usr/local/bin/
          # rm packer.zip
          sudo apt-get update && sudo apt-get install -y packer

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Set up AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "AWS credentials are set."
      - name: Set Commit ID
        id: set_commit_id
        run: echo "COMMIT_ID=${GITHUB_SHA::8}"

      - name: Debug COMMIT_ID
        run: echo "COMMIT_ID=${{ steps.set_commit_id.outputs.COMMIT_ID }}"

      - name: Initialize Packer
        run: |
          packer init ubuntu-ami.pkr.hcl

      - name: Build AMI with Packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRO_PUBLIC_KEY: ${{ secrets.DISTRO_PUBLIC_KEY }}
          COMMIT_ID: ${{ steps.set_commit_id.outputs.COMMIT_ID }}
        run: |
          packer build -var "public_key=${DISTRO_PUBLIC_KEY}" -var "commit_id=${COMMIT_ID}" ubuntu-ami.pkr.hcl

